ls
cd python3 Hex.py -p1 "agents.Group23.MCTSAgent MCTSAgent" -p1Name "P1" p2 "agent.Group23.MCTSAgent MCTSAgent" -p2Name "P2"
python3 Hex.py -p1 "agents.Group23.MCTSAgent MCTSAgent" -p1Name "P1" p2 "agent.Group23.MCTSAgent MCTSAgent" -p2Name "P2"
python3 Hex.py -p1 "agents.Group23.MCTSAgent MCTSAgent" -p1Name "P1" -p2 "agent.Group23.MCTSAgent MCTSAgent" -p2Name "P2"
python3 Hex.py -p1 "agents.Group23.MCTSAgent MCTSAgent" -p1Name "P1" -p2 "agents.Group23.MCTSAgent MCTSAgent" -p2Name "P2"
python3 Hex.py -p1 "agents.Group23.MCTSAgent MCTSAgent" -p1Name "P1" -p2 "agents.Group23.MCTSAgent MCTSAgent" -p2Name "P2"
python3 Hex.py -p1 "agents.Group23.MCTSAgent MCTSAgent" -p1Name "P1" -p2 "agents.Group23.MCTSAgent MCTSAgent" -p2Name "P2"
python3 Hex.py -p1 "agents.Group23.MCTSAgent MCTSAgent" -p1Name "P1" -p2 "agents.Group23.MCTSAgent MCTSAgent" -p2Name "P2"
python3 Hex.py -p1 "agents.Group23.MCTSAgent MCTSAgent" -p1Name "P1" -p2 "agents.Group23.MCTSAgent MCTSAgent" -p2Name "P2"
python3 Hex.py -p1 "agents.Group23.MCTSAgent MCTSAgent" -p1Name "P1" -p2 "agents.Group23.MCTSAgent MCTSAgent" -p2Name "P2"
python3 Hex.py -p1 "agents.Group23.MCTSAgent MCTSAgent" -p1Name "P1" -p2 "agents.Group23.MCTSAgent MCTSAgent" -p2Name "P2"
python3 Hex.py -p1 "agents.Group23.MCTSAgent MCTSAgent" -p1Name "P1" -p2 "agents.Group23.MCTSAgent MCTSAgent" -p2Name "P2"
python3 Hex.py -p1 "agents.Group23.MCTSAgent MCTSAgent" -p1Name "P1" -p2 "agents.Group23.MCTSAgent MCTSAgent" -p2Name "P2"
python3 Hex.py -p1 "agents.Group23.MCTSAgent MCTSAgent" -p1Name "P1" -p2 "agents.Group23.MCTSAgent MCTSAgent" -p2Name "P2"
python3 Hex.py -p1 "agents.Group23.MCTSAgent MCTSAgent" -p1Name "P1" -p2 "agents.Group23.MCTSAgent MCTSAgent" -p2Name "P2"
python3 Hex.py -p1 "agents.Group23.MCTSAgent MCTSAgent" -p1Name "P1" -p2 "agents.Group23.MCTSAgent MCTSAgent" -p2Name "P2"
python3 Hex.py -p1 "agents.Group23.MCTSAgent MCTSAgent" -p1Name "P1" -p2 "agents.Group23.MCTSAgent MCTSAgent" -p2Name "P2"
